const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{tipoIndex: 0},
	{Física: 0},
	{Sólido: 0},
	{lixeira_plastico: 0},
	{lixeira_vidro: 0},
	{lixeira_metal: 0},
	{posX_inicial: 0},
	{posY_inicial: 0},
	{ArrastarSoltar: 0},
	{lixo: 0},
	{pontuacao: 0},
	{pontos: 0},
	{a: 0},
	{Mouse: 0},
	{ponto: 0},
	{Text: 0},
	{Cronômetro: 0},
	{seisSeis: 0},
	{inicioDeJogo: 0},
	{voltarParaOInicio: 0},
	{titulo: 0},
	{Botão2: 0},
	{lixeira_papel: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{tempo: 0}
];

self.InstanceType = {
	lixeira_plastico: class extends self.ISpriteInstance {},
	lixeira_vidro: class extends self.ISpriteInstance {},
	lixeira_metal: class extends self.ISpriteInstance {},
	lixo: class extends self.ISpriteInstance {},
	pontos: class extends self.ITextInstance {},
	a: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	ponto: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	seisSeis: class extends self.ITextInstance {},
	inicioDeJogo: class extends self.ITextInstance {},
	voltarParaOInicio: class extends self.IButtonInstance {},
	titulo: class extends self.ITextInstance {},
	Botão2: class extends self.IButtonInstance {},
	lixeira_papel: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}